config/initializers/controlled_vocabularies.rb, lib/oregon_digital/controlled_vocabularies/creator.rb, lib/oregon_digital/metadata/form_to_attributes.rb, lib/oregon_digital/vocabularies/dummycreator.rb
=> Make creator controlled vocabulary turn strings into URIS.

CONTRIBUTING.md
Borrowed heavily from Hydra/Sufia's files, but edited and slimmed down some areas.
Fixes #531
=> First pass at CONTRIBUTING.md

Gemfile, Gemfile.lock, Rakefile, app/jobs/create_derivatives_job.rb, config/initializers/resque.rb, config/routes.rb
=> Retry Derivative Jobs on Failure

app/assets/stylesheets/theme.css.scss, app/controllers/catalog_controller.rb, app/models/datastream/oregon_rdf.rb, lib/oregon_digital/catalog/sort_fields.rb
This is going to require reindexing everything.
Closes #421 
Do we want sorting by added/modified?
=> Add sorting by title.

app/helpers/collections_helper.rb, spec/features/catalog_spec.rb
=> Strip quotes from book search follow-through.

app/controllers/sets_controller.rb, spec/controllers/sets_controller_spec.rb, spec/factories/generic_collection.rb
=> Only display reviewed sets.

app/models/generic_asset.rb, lib/oregon_digital/catalog/sort_fields.rb, lib/oregon_digital/date_sorting.rb, spec/models/generic_asset_spec.rb
This adds support for dates of the following formats:
2011-01-01
2011-01
2011-2014
2011nonsensehere
Closes #652 and #650
=> Add date sorting.

Gemfile.lock
=> Updated puma.

lib/oregon_digital/date_sorting.rb
DateTime.parse was reading 20th Cent. as "year 20", which broke a lot.
=> Make date sorting less flexible

app/models/ability.rb
=> Allow users to download full res of audio

app/views/catalog/index.atom.builder
=> Use atom feed from later version of blacklight.

app/jobs/migrate_compounds_job.rb
=> Allow for bad data in solr.

app/models/datastream/oregon_rdf.rb
=> Allow for non-generic assets to be pulled via from_solr

lib/oregon_digital/catalog/facets.rb, lib/oregon_digital/date_sorting.rb, spec/models/generic_asset_spec.rb
=> Add decade facets.

app/controllers/downloads_controller.rb, spec/controllers/downloads_controller_spec.rb, spec/factories/generic_asset.rb
=> Fix crash on downloading GenericAsset data

app/controllers/application_controller.rb, spec/controllers/downloads_controller_spec.rb
Redirects access denied errors using hydra controller behavior code
=> Don't throw Internal Server Error on access denied

LICENSE
Closes #721 
Couple edits we may need - is identifying our collaboration as Oregon Digital warranted?
I've back-licensed all of OD under Apache until the year of the first commit of this repo.
@kestlund, @evvivaweinraub @boockm Any complaints?
=> Add LICENSE [ci skip]

app/assets/stylesheets/theme.css.scss
just a quick fix to get rid of item before big Bootstrap3 re-write
=> fixes #707

README.md
=> Switch to CircleCI Badge

app/models/datastream/oregon_rdf.rb, spec/models/generic_asset_spec.rb
This indexes latitude/longitude fields in solr for spatial searches.
=> Spatial Search Indexing

lib/oregon_digital/controlled_vocabularies/repos.rb
@jsimic notes that we'll use ulan heavily with repository for the big art colls.
=> adding ulan to repos

app/assets/stylesheets/theme.css.scss
Refined to include active as well.
=> CSS Compound Object

app/models/datastream/oregon_rdf.rb
=> Added Translator to Creator.

app/models/contact_form.rb
=> Updated contact form send to address to dsc.

lib/oregon_digital/controlled_vocabularies/repos.rb
=> adding lcsh to repo

app/models/datastream/oregon_rdf.rb
This reverts commit 78eecea15e239597a7bcd4b227cf6e3ac21088db.
=> Revert "Replace VRA with op_ns"

app/models/datastream/oregon_rdf.rb
by request of Julia, for Mongolian Altai
=> make hasVersion searchable

app/views/catalog/_home_text.html.erb
edited to remove Oregon University System
=> edited homepage text

config/initializers/ingest_form_map.rb, config/locales/oregondigital.en.yml
=> Added LCCN to Ingest form. Added label to facet field.

app/views/sets/_home_text.html.erb
Moved Tribal Legacies to Other Resources
=> collections-page-edit

app/models/datastream/oregon_rdf.rb, config/initializers/ingest_form_map.rb
=> fixing translator field

lib/oregon_digital/controlled_vocabularies/work_type.rb
=> Add Thesaurus for Graphic Materials to Work Type controlled vocab.

config/initializers/controlled_vocabularies.rb, lib/oregon_digital/vocabularies/rights.rb
I'm having issues with using opaquenamespace.org/ns/rights/educational in folklore
=> add ns to opns rights

config/initializers/session_store.rb
=> Use cache store for sessions

config/initializers/ingest_form_map.rb
=> Added Water Basin to Ingest Form map.

public/503.html
=> Created new 503 static page.

lib/oregon_digital/controlled_vocabularies/organization.rb
to resolve issue with Chinavine contributingInstitution see 835
=> add creator

lib/oregon_digital/oai/concern.rb, lib/oregon_digital/oai/model/solr_instance_decorator.rb, spec/controllers/oai_controller_spec.rb, spec/features/oai_spec.rb
fixes #955 
there's probably a more elegant way to do this...
=> first try at earliest/latest date

lib/oregon_digital/oai/provider.rb
=> raised limit to 100

lib/oregon_digital/oai/qualified_dublin_core.rb
=> Updated XSD location for Qualified Dublin Core response format.

lib/oregon_digital/oai/concern.rb, lib/oregon_digital/oai/dublin_core.rb, lib/oregon_digital/oai/qualified_dublin_core.rb
=> Added Format to responses and mappings.

lib/oregon_digital/catalog/search_fields.rb
=> Added identifier to search fields for Advanced Search.

vendor/assets/javascripts/bookreader/BookReader.js
=> Changed https to http.

lib/oregon_digital/oai/concern.rb, lib/oregon_digital/oai/model/solr_instance_decorator.rb, spec/features/oai_spec.rb
=> temp fix for oai formats

app/decorators/generic_asset_decorator.rb, spec/features/compound_object_spec.rb
=> disable od_content

lib/oregon_digital/oai/model/active_fedora_wrapper.rb, spec/lib/oregon_digital/oai/model/active_fedora_wrapper_spec.rb
=> chunk up query

.gitmodules
the url in .gitmodules had not been updated.
=> fix jetty submodule

app/controllers/thumbnails_controller.rb, config/routes.rb, spec/controllers/thumbnails_controller_spec.rb
=> handle get thumbnail

lib/oregon_digital/oai/model/active_fedora_wrapper.rb, spec/features/oai_spec.rb
=> check primarySet for oai

lib/oregon_digital/oai/model/active_fedora_wrapper.rb
fixes #1029 
also removes unnecessary solr query/extract labels method, uses the instance already loaded from solr to get labels.
=> remove extra queries

lib/oregon_digital/oai/model/active_fedora_wrapper.rb, lib/oregon_digital/oai/model/solr_instance_decorator.rb
=> remove round of solr_queries

lib/oregon_digital/controlled_vocabularies/subject.rb
=> Added ULAN to LC Subject.

lib/oregon_digital/oai/provider.rb
Fixes #1054 
Return 50 records in a response instead of 100.
=> oai return less

app/decorators/image_decorator.rb
=> Added image/png media type to small image viewer list.

lib/oregon_digital/catalog/search_fields.rb
=> Added isPartOf field as search field for Advanced Search.

app/models/bulk_task_child.rb, lib/tasks/hybag.rake, spec/controllers/oai_controller_spec.rb, spec/features/oai_spec.rb, spec/fixtures/fixture_triples.nt, spec/webmocks/format.rb
Also updated webmock for format URI fetch.
Added check for existing Format URI on Ingest.
Fixes #1088 
Fixes #942
=> Update Format URI in ingest and specs

app/models/datastream/oregon_rdf.rb, config/initializers/ingest_form_map.rb
Add Hydrologic Unit Code and LLID properties to system and ingest form
map.
Fixes #1093 
Fixes #1094
=> Add Hydrologic Unit Code and LLID properties

app/models/datastream/oregon_rdf.rb, config/initializers/ingest_form_map.rb, lib/oregon_digital/oai/concern.rb
Add Recipient field to system with Creator CV, ingest form map and OAI.
Fixes #1101
=> Add Recipient field

config/initializers/ingest_form_map.rb
Add Geobox, Barcode, photographOrientation and objectOrientation fields
to the ingest form mapping.
Fixes #1100 
Fixes #1097 
Fixes #1095
=> Add multiple existing fields to Ingest Form

app/assets/javascripts/bookreader/oregondigital_bookreader.js.coffee
=> update bookreader search url to remove leading/trailing spaces

lib/oregon_digital/oai/model/solr_instance_decorator.rb
=> check for rdf_label

app/helpers/ingest_helper.rb
=> Sort Set dropdown by title. Add set pid.

app/views/static/copyright.html.erb
=> Change Europeana URIs to opaquenamespace.org

lib/tasks/sitemap_gen.rake
fixes #1050 
basic rake task to grab all of the assets/sets urls and print xml.
also an update task, grabs new assets/sets and appends. method of appending might be a little wonky though.
=> add rake task

lib/oregon_digital/oai/model/active_fedora_wrapper.rb, spec/features/oai_spec.rb, spec/lib/oregon_digital/oai/model/active_fedora_wrapper_spec.rb
=> only keep corrupt set handling

lib/oregon_digital/oai/model/active_fedora_wrapper.rb
fixes #1147 
(or rather, this PR plus two others)
=> use solr for labels in build_wrapped

lib/oregon_digital/oai/model/active_fedora_wrapper.rb, spec/controllers/oai_controller_spec.rb
=> accept oai identifier

lib/oregon_digital/oai/model/active_fedora_wrapper.rb, spec/controllers/oai_controller_spec.rb, spec/lib/oregon_digital/oai/model/active_fedora_wrapper_spec.rb
=> should return nil when empty

lib/oregon_digital/controlled_vocabularies/scientific.rb
Also added custom fetch code to handle wikidata as well as retain itis
and ubio support.
Fixes #1143
=> Add wikidata to Scientific CV

config/initializers/controlled_vocabularies.rb, lib/oregon_digital/controlled_vocabularies/subject.rb, lib/oregon_digital/vocabularies/osuacademicunits.rb
=> Add OSU Academic Units vocab to system, Subjects CV

lib/oregon_digital/oai/concern.rb, spec/features/oai_spec.rb
=> add set to uri list

app/assets/stylesheets/theme.css.scss
Fixes #1177 Quick repair to slideshow
=> Repair slide formatting

app/assets/stylesheets/sets_template.css.scss, app/assets/stylesheets/sets_uo_template.css.scss, app/assets/stylesheets/theme.css.scss
Minor CSS tweaks for set collection slideshows.
=> Minor CSS tweaks.

app/views/static/about.html.erb
=> Fixes #1184

app/assets/stylesheets/sets_template.css.scss
A minor typographical CSS change.
=> Some minor typographical css

app/models/datastream/oregon_rdf.rb
=> Added :facetable to Contributor

app/models/datastream/oregon_rdf.rb, config/initializers/controlled_vocabularies.rb, lib/oregon_digital/controlled_vocabularies/series_name.rb, lib/oregon_digital/vocabularies/seriesname.rb
=> make seriesName facetable

app/controllers/oembed_controller.rb, config/app.yml.default, spec/controllers/oembed_controller_spec.rb, spec/controllers/thumbnails_controller_spec.rb
=> fix default_url_host

.circleci/config.yml, docker/Dockerfile-ruby-phantomjs
use image (for circleci) that's now stashed in the OD docker hub
=> move image into od

config/application.rb
=> Remove X-Frame-Options as default header.

Gemfile, Gemfile.lock, docker/Dockerfile
=> use ruby-vips with fix for centos

Gemfile, Gemfile.lock, docker/Dockerfile
=> use github repo for logger gem

docker-compose.yaml
=> specify mongo version

app/models/datastream/oregon_rdf.rb, lib/oregon_digital/controlled_vocabularies/license.rb
=> Create License CV and add to license field.

config/initializers/ingest_form_map.rb
=> Add License field to ingest form.

lib/tasks/create_profiles.rake
=> Profile rake task

lib/tasks/create_profiles.rake
this info would be needed in https://github.com/OregonDigital/hyrax-migrator/issues/180
=> add checksums info to profile

app/models/datastream/oregon_rdf.rb, lib/oregon_digital/catalog/search_fields.rb
Also remove Donor from search fields on Advanced Search, since the field will have a facet now that can be used.
Related to #1271
=> Change Donor to controlled, with Creator CV.

app/models/datastream/oregon_rdf.rb, lib/oregon_digital/vocabularies/sheetmusic.rb
=> switch sheetmusic preds

app/models/datastream/oregon_rdf.rb
fixes problem that string uris do not display.
numerous coll ticket references (eg 755-760) to this.
=> coerce only controlled

app/models/datastream/oregon_rdf.rb
use a list of string uris that should be allowed to display, in order to allow findingAid but exclude replacesUrl.
=> use whitelist

config/initializers/ingest_form_map.rb
=> Add onPages property to Ingest Form.

lib/oregon_digital/guest_user.rb
Fixes #1341 
I have no dev environment so this is totally untested.  It may not even pass syntax checking....
=> Update guest users' IP addresses

Gemfile, Gemfile.lock, lib/oregon_digital/controlled_vocabularies/organization.rb
=> Add lcnames vocab to Organization CV

lib/hydra/derivatives/video_filesystem.rb
=> Add -nostdin option flag to ffmpeg call.

lib/hydra/derivatives/video_filesystem.rb
=> Change flags to verbosity 0 and nostats to suppress output

lib/hyrax/migrator/asset_status.rb, lib/hyrax/migrator/crosswalk_metadata.rb, lib/hyrax/migrator/crosswalk_metadata_preflight.rb, lib/hyrax/migrator/preflight_checks.rb, lib/hyrax/migrator/required_fields.rb, lib/tasks/preflight_tools/preflight.rake
=> adding preflight

lib/hyrax/migrator/export.rb, lib/hyrax/migrator/export_reporter.rb
fixes #https://github.com/OregonDigital/hyrax-migrator/issues/216
=> add exporter reporting

lib/hyrax/migrator/preflight_checks.rb, lib/hyrax/migrator/visibility_lookup.rb, lib/hyrax/migrator/visibility_lookup_preflight.rb
pull update for PreflightChecks as required in https://github.com/OregonDigital/hyrax-migrator/pull/221#issuecomment-650400767
=> update preflight checks as required in hyrax-migrator/pull/221

app/models/datastream/oregon_rdf.rb, lib/oregon_digital/oai/concern.rb
=> Make Owner field controlled.

app/models/datastream/oregon_rdf.rb, config/initializers/ingest_form_map.rb, config/locales/oregondigital.en.yml
=> Remove LCCN field, not used or needed.

lib/tasks/create_profiles.rake
fixes https://github.com/OregonDigital/hyrax-migrator/issues/226 (the profiler part. will make a second ticket to add to verification process in migration gem)
=> handle od_content field

app/models/datastream/oregon_rdf.rb, lib/oregon_digital/oai/concern.rb
=> Make Designer controlled. Add to OAI config.

lib/tasks/create_profiles.rake
fixes https://github.com/OregonDigital/hyrax-migrator/issues/238
=> fix contents

lib/hyrax/migrator/cpd_check.rb, lib/hyrax/migrator/crosswalk_metadata_preflight.rb, lib/hyrax/migrator/preflight_check_services.rb, lib/hyrax/migrator/preflight_checks.rb, lib/hyrax/migrator/visibility_lookup_preflight.rb
get latest changes to Hyrax Migrator Preflight tools
=> updates to preflight

lib/oregon_digital/controlled_vocabularies/publisher.rb
=> Add lc_orgs vocab to Publisher CV.

lib/hyrax/migrator/export.rb, lib/hyrax/migrator/metadata_profiler.rb, spec/lib/hyrax/migrator/metadata_profiler_spec.rb
fixes https://github.com/OregonDigital/hyrax-migrator/issues/271
=> Fix singles in profiler

lib/hyrax/migrator/export.rb, lib/tasks/migration/export_bags.rake, spec/features/collection_facets_spec.rb
fixes https://github.com/OregonDigital/hyrax-migrator/issues/269
=> Refactor export

lib/oregon_digital/controlled_vocabularies/organization.rb
Part of #1350 
This expands the existing Organization CV so the URI changes on #1350 can be completed.
=> Add ONS repository vocab to Org CV.

lib/tasks/migration/export_bags.rake, spec/features/collection_facets_spec.rb
fix incorrectly named method calls in rake task export_bags
=> fix method name

config/initializers/controlled_vocabularies.rb, lib/oregon_digital/controlled_vocabularies/geographic.rb, lib/oregon_digital/vocabularies/tfddbasins.rb
=> Add TFDD Basins vocab to system, Geographic CV.

.circleci/config.yml, app/controllers/catalog_controller.rb, app/models/datastream/oregon_rdf.rb, config/initializers/ingest_form_map.rb, lib/oregon_digital/catalog/defaults.rb, lib/oregon_digital/oai/concern.rb
=> adding landscapeArchitect

app/models/datastream/oregon_rdf.rb, config/initializers/controlled_vocabularies.rb, lib/oregon_digital/controlled_vocabularies/series_name.rb, lib/oregon_digital/vocabularies/seriesname.rb
=> make seriesName uncontrolled

app/views/shared/sets/_footer.html.erb
=> Update footer partial, remove mobile site links

lib/oregon_digital/controlled_vocabularies/scientific.rb
=> Add LCSH vocab to Scientific CV
