OregonDigital/oregondigital

lib/oregon_digital/controlled_vocabularies/organization.rb
This lets us use the console to force a label if fetch is being wonky - as it's doing in dbpedia.
=> Allow forced organization label

app/jobs/fetch_all_job.rb, lib/oregon_digital/rdf/deep_fetch.rb, spec/models/generic_asset_spec.rb
Because of this, fetch jobs are taking hours per fetch, and there's thousands of fetch jobs, when a full reindex takes 6 hours.
This process is only useful if a label changes. My theory is that's pretty rare.
=> Disable fixing fedora index on fetch

Gemfile, Gemfile.lock
The previous Mongo implementation had an index built on Object, which exceeded the 1024 Byte limit for MongoDB document indexes. When this happened it broke the index for those subjects, and so not all items would get returned. Due to this we'd end up with RDF::Resources without full graphs which would then get persisted - hence no label.
=> Don't index object for Mongo triples

lib/oregon_digital/rdf/controlled.rb
This re-fetches if it can't find an authoritative label (likely if there's only non-english labels in the repository being used.)
=> Re-fetch if no authoritative label

app/models/datastream/oregon_rdf.rb
- Mods URIs now have a slash before the # character, as our controlled
vocab info says they should
- RDA Registry URIs now have a # character in them and resolve to a
live page, but I have no idea if they're definitely correct
=> Fix predicate URIs

config/application.rb, lib/conneg_middleware.rb
Rails has a bug with priority in content negotiation and this is a hack to fix
it until it's fixed upstream. See https://github.com/rails/rails/issues/9940
=> Add middleware to strip */* from accept headers.

app/views/devise/mailer/reset_password_instructions.html.erb
From http://stackoverflow.com/questions/19018657/rails-4-devise-password-reset-is-always-giving-a-token-is-invalid-error-on
Fixes #868
=> Updating devise edit password url to use the real token

lib/oregon_digital/controlled_vocabularies/organization.rb
This was making whatever was returned from typeahead the authoritative label.
=> Remove preferring hidden label.

lib/oregon_digital/rewrite_generator.rb, spec/lib/oregon_digital/rewrite_generator_spec.rb
This stops nginx from matching early.
=> Update viewer string to be more strict.

lib/oregon_digital/controlled_vocabularies/geographic.rb
=> Added trailing slash to result ID from Geonames search.

config/environments/production.rb
Changes production log to :warn instead of :info to save on log file space
=> Fix log levels

config/environments/production.rb
Lets us specify facility by overriding the syslog used by
Syslog::Logger:
http://ruby-doc.org/stdlib-2.0.0/libdoc/syslog/rdoc/Syslog/Logger.html#method-c-syslog-3D
=> Override syslog for ruby 2.0.0

app/assets/javascripts/prevent-double-click.js.coffee, app/views/catalog/_admin_show_tools.html.erb, app/views/reviewer/_index_default.html.erb
Clicks have to be 8 seconds apart for them to be counted.  Ideally we'd
have a visual indicator that the control had been clicked, but
prevention is more important than making it nice right now.
closes #919
=> Prevent double-click for review button and link

config/environments/development.rb, config/environments/test.rb, spec/spec_helper.rb, spec/support/resque_inline.rb
Removes multiple deprecation warnings (OD2 is a completely rewritten codebase, and OD1 won't be updating to the newest Hydra/Rails, so I see no value in these) and adds an option to skip coverage reporting when running tests.
Makes tests a bit faster, and output significantly more readable, especially when just trying to run a handful of tests.
=> Fix test output

app/controllers/sets_controller.rb
This may help with #878, and fixes what I *think* is a legitimate bug: non-index set controller actions are not getting the set context.
=> Ensure @collection / @collections are never nil

app/models/generic_asset.rb, app/views/catalog/_compound.html.erb, config/environments/test.rb, spec/features/compound_object_spec.rb
fixes #1007 
So this expires the cache of each member if a child or parent is saved. does not yet address the issue of soft_destroy.
=> cache cpd table

app/views/bulk_tasks/show.html.erb, spec/features/bulk_task_spec.rb
- Removes JS requirement to speed up tests since they don't need JS
- Clicks the child task link directly instead of assuming the last one
in the database will work
=> Fix bulk task spec

lib/oregon_digital/controlled_vocabularies/subject.rb, lib/oregon_digital/rdf/controlled.rb, lib/oregon_digital/vocabularies/itis.rb
Add fetch_itis and fetch_ubio calls to Subject controlled vocab.
Change ITIS vocab definition to 'https'. Change fetch_itis to use
'https'.
Fixes #1078
=> Change ITIS fetch to always be https

config/initializers/controlled_vocabularies.rb, lib/oregon_digital/controlled_vocabularies/format.rb, lib/oregon_digital/vocabularies/mediatype.rb
Add the SPAR Ontologies Mediatype URIs as a vocabulary and add to Format
controlled vocabulary. Use custom fetch method to go straight to the
RDF/XML file. The redirects from https://w3id.org/spar to
http://www.sparontologies.net break content negotiation with our
current setup.
Fixes #1084 
Also related to #940
=> Add support for SPAR Ontologies Mediatype URIs

app/assets/stylesheets/ingest.css.scss, app/views/ingest/_ingest_fields.html.erb, spec/features/ingest_form_spec.rb
This adds a URI button when an Ingest Form field is controlled, so
instead of just showing the label the URI underneath it is also available. Button opens the URI in a new window, or can be used for copying the link to clipboard.
Fixes #1098 
Here's what it looks like:
=> Add URI button to Ingest Form on controlled fields

lib/oregon_digital/vocabularies/rights.rb
I mistakenly added a slash at the end of the new properties, since the Europeana URIs had them. Our new ones don't.
=> Remove slashes from end of new properties

README.md, app/helpers/ingest_helper.rb, config/initializers/ingest_form_map.rb, docker/test.sh, lib/oregon_digital/catalog/decorators.rb, lib/oregon_digital/controlled_vocabularies/set.rb, spec/features/ingest_form_spec.rb, spec/features/templates_spec.rb, spec/models/generic_collection_spec.rb, spec/support/ingest_form.rb, spec/support/matchers/ingest_form.rb
Fixes #701 indirectly.  Hard-codes a new ingest form group for collections (set and primary set) to use a dropdown instead of a text input.  The code is very special-case, and we'll probably want a better way to handle dropdowns more generally, but this will almost certainly deal with set typos, as nobody can directly type now.
This PR also does a little housekeeping on docker testing, which could be put into its own PR if desired; I just found some issues when testing that needed to be addressed.
=> Create dropdown for sets

batch/.gitignore, docker-compose.yaml
Sets up docker-compose.yml to mount a local directory as the default batch directory, and adds that directory to the repo.
=> Add batch directory for docker

lib/oregon_digital/date_sorting.rb, spec/features/advanced_search_spec.rb, spec/models/generic_asset_spec.rb
Fixes #1169 
Modify decade facet processor to include award date
If no Date is present, fall back to Award Date.
Added date issued and date created to Decade facet.
Updated and clarified specs
Change date value checks to nil?
Clarified CSS selector for facets, since now Decade facet is present
Updated specs to use factory's created date, and changed date to help differentiate returned values
Clarified date sorting with nil date
=> Add more dates to Decade facet processor.

app/decorators/document_decorator.rb
Fixes #1023 
Each page has it's own datastream, which is fed into leafMetadata, which
is then passed on to the BookReader viewer via the JSON call. The
leafMetadata had pages out of order, so while the pages displayed in
order in the viewer, when it queried a page to get its height, it was
returning the height from a different page, and the different height
caused the calculations to be off and some images to be distorted.
This changes page_datastreams to return order based on the page number
in the datastreams hash key.
=> Modified page_datastreams to return sorted order

lib/oregon_digital/oai/concern.rb
It was already mapped in Date field.
Fixes #1172
=> Remove awardDate from Description mapping

app/controllers/bulk_tasks_controller.rb, app/views/bulk_tasks/all_tasks.html.erb, config/routes.rb
No ticket for this but the Bulk Tasks main page takes way too long to render each time.
Changed the Bulk Tasks page to not show all entries, only the 30 most
recent ones. The full list is still available on a new page.
=> Changes Bulk Tasks to show recent, adds All page

vendor/assets/javascripts/bookreader/BookReader.js
Closes #1229 
Closes #1226
Removing the embedded navbar function doesn't appear to affect my local bookreader in any negative way, but should remove the false-positives which generated the above-mentioned tickets.
=> Remove bookreader's embedded navbar init

lib/oregon_digital/controlled_vocabularies/creator.rb
Fixes #1253 
Strings are rejected as not being in the CV now.
=> Remove initialize and assign_subject that auto-creates URIs in Creator CV.

lib/oregon_digital/controlled_vocabularies/creator.rb
Fixes #1255 
This is the same method that the Subject CV has, forces use of the id.loc.gov links out of the JSON response that QA gets.
=> Add loc_reponse_to_qa method

config/initializers/controlled_vocabularies.rb, lib/oregon_digital/controlled_vocabularies/rights_statement.rb, lib/oregon_digital/vocabularies/rightsstatements.rb
Fixes #1287 
Add RightsStatements.org vocabulary to the system, including the initializer, and add to the RightsStatement Controlled Vocabulary. Wrote custom fetch method to retrieve RDF from the /data URIs for labels.
```ruby
[10] pry(main)> rsnc = OregonDigital::ControlledVocabularies::RightsStatement.new (RDF::URI('http://rightsstatements.org/vocab/NoC-US/1.0/'))
=> #<OregonDigital::ControlledVocabularies::RightsStatement:0x2afddecdcfc4(default)>
[11] pry(main)> rsnc.rdf_label
=> ["http://rightsstatements.org/vocab/NoC-US/1.0/"]
[12] pry(main)> rsnc.fetch
=> nil
[13] pry(main)> rsnc.rdf_label
=> ["No Copyright - United States"]
```
=> Add RightsStatements.org vocabulary, add to CV.

Gemfile, Gemfile.lock, app/models/datastream/oregon_rdf.rb, config/initializers/controlled_vocabularies.rb, lib/oregon_digital/controlled_vocabularies/access_restrictions.rb, lib/oregon_digital/vocabularies/accessrestrict.rb
Fixes #1292 
Creates a new vocabulary for Access Restrictions at opaquenamespace.org, and then adds that to a new Controlled Vocabulary, which is then applied to the accessRestrictions fields. The values are set to facet as well.
Also a small bump to ruby-vips, the original version was not installing/building any more.
Access Restrictions field now controlled with both values:
Facet:
=> Add Vocabulary and CV for Access Restrictions. Bump to ruby-vips.

app/views/catalog/_small_image_viewer.html.erb
Fixes #1303 
I can't take a screenshot with the image title popup, but result code is:
```html
<div id="small-image-viewer">
  <img src="/media/medium-images/8/9/oregondigital-j67331498.jpg"
    alt="Test jpg viewer alt text - Heathman Hotel"
    title="Test jpg viewer alt text - Heathman Hotel">
</div>
```
=> Add quotes around alt and title attributes.

lib/tasks/create_profiles.rake
this info is needed for verification of derivatives in migration ticket https://github.com/OregonDigital/hyrax-migrator/issues/195
Usage:
```
$ cat /data1/batch/profiles/derivatives_info_pidlist.txt
oregondigital:df661w36p
oregondigital:df70dp55t
oregondigital:df72jn67c
oregondigital:fx719p324
oregondigital:fx719q37q
oregondigital:fx719q99q
oregondigital:fx71bc60m
oregondigital:df72jn018
oregondigital:df72jn000
RAILS_ENV=production bundle exec rake create_profiles pids=/data1/batch/profiles/derivatives_info_pidlist.txt export_path=/data1/batch/profiles/derivatives_info
```
It should generate profiles at `/data1/batch/profiles/derivatives_info` and the yml files should contain the hash `derivatives_info` when available.
Sample output: …
=> retrieve derivatives info for hyrax-migrator

lib/tasks/create_profiles.rake
fixes https://github.com/OregonDigital/hyrax-migrator/issues/205
escape_chars escapes double quotes in string values
=> escape special characters for valid yml output

app/models/datastream/oregon_rdf.rb
Fixes #897 
Fields are controlled but shouldn't be added to the facet list.
=> Make placeOfPublication and placeOfProduction controlled.

app/models/datastream/oregon_rdf.rb, config/initializers/controlled_vocabularies.rb, lib/oregon_digital/controlled_vocabularies/publisher.rb, lib/oregon_digital/oai/concern.rb, lib/oregon_digital/vocabularies/publisher.rb
For part of #898 
Create Publisher vocabulary and Publisher controlled vocabulary with several vocabs, and make the field use that new CV.
=> Add Publisher vocab and CV, make field controlled.

lib/hyrax/migrator/metadata_profiler.rb
for use with https://github.com/OregonDigital/hyrax-migrator/issues/247
adds visibility to the profile created by the MetadataProfiler, eg
visibility:
-  "public"
=> add read_groups to profiler

lib/hyrax/migrator/checksums_profiler.rb
we are only using the md5hex when running verification.
=> only get md5hex

lib/hyrax/migrator/export.rb
In export.rb, the bag_finisher method is for updating the bag after changes have been made.
I thought that the BagIt method write_bag_info updated the bag-info, but not on its own. This PR inserts a few lines of code in bag_finisher to set the date to current date before calling write_bag_info.
=> update bag_info date

Gemfile, Gemfile.lock, config/initializers/controlled_vocabularies.rb, lib/oregon_digital/controlled_vocabularies/scientific.rb, lib/oregon_digital/vocabularies/scispecies.rb
I was able to track down the gem dependency causes.
Disabled rspec_junit_formatter gem. That repo was archived, and I don't think we need it.
The code4lib oai gem had some recent-ish updates which updated dependencies, so I pinned to the tag of the release that we were using.
If this gets merged, I think #1563 should be able to update and then merge as well.
=> Add species vocab to Scientific CV

Gemfile, Gemfile.lock, config/app.yml.default, spec/factories/generic_asset.rb, spec/models/generic_asset_spec.rb
Also update set-content github repo to https.
Factory for generic asset was making a created date of now - 1000 days + a sequence counter. That date was now either at the end of 2019 (ok) or start of 2020 (not ok), which affected the date decade facet checking for 2010-2019.
=> Update ruby-oai gem, had gone back too old before.
